#
#

#
# begin_clean.sh
# unit_test.sh
#

#:<<start_block
CURRENT_PATH=`pwd`
SYSTEM_DIR=$CURRENT_PATH/system
LIBRARY_DIR=$CURRENT_PATH/library
LIBRARY_DIR_COMMON=$CURRENT_PATH/library/common
MODULES_DIR=$CURRENT_PATH/modules
RUNNING_DIR=$CURRENT_PATH/running
RUNNING_MODULES_DIR=$CURRENT_PATH/running/modules
FINAL_DIR=$RUNNING_DIR/final

TOOLS_DIR=$CURRENT_PATH/tools
TOOLS_KICKSTART_DIR=$TOOLS_DIR/kickstart
TOOLS_KICKSTART_PARTITION_DIR=$TOOLS_KICKSTART_DIR/partition
TOOLS_INSMOD_DIR=$TOOLS_DIR/insmod
TOOLS_CORE_DIR=$TOOLS_DIR/core
TOOLS_CORE_KICKSTART_DIR=$TOOLS_CORE_DIR/kickstart

SRC_DIR=$SYSTEM_DIR:$LIBRARY_DIR:$LIBRARY_DIR_COMMON:$MODULES_DIR:$RUNNING_DIR:$RUNNING_MODULES_DIR:$TOOLS_DIR:$TOOLS_KICKSTART_DIR:$TOOLS_KICKSTART_PARTITION_DIR:$TOOLS_INSMOD_DIR:$TOOLS_CORE_DIR:$TOOLS_CORE_KICKSTART_DIR

UNIT_TEST_DIR=unit_test
UINT_TEST_SYSTEM_DIR=$UNIT_TEST_DIR/system
UINT_TEST_LIBRARY_DIR=$UNIT_TEST_DIR/library
UINT_TEST_LIBRARY_DIR_COMMON=$UNIT_TEST_DIR/library/common
UINT_TEST_PROCESS_DIR=$UNIT_TEST_DIR/process
UINT_TEST_MODULES_DIR=$UNIT_TEST_DIR/modules
UINT_TEST_RUNNING_DIR=$UNIT_TEST_DIR/running
UINT_TEST_TOOLS_DIR=$UNIT_TEST_DIR/tools
UINT_TEST_TOOLS_KICKSTART_DIR=$UINT_TEST_TOOLS_DIR/kickstart
UINT_TEST_TOOLS_KICKSTART_PARTITION_DIR=$UINT_TEST_TOOLS_KICKSTART_DIR/partition
UNIT_TEST_TOOLS_CORE_DIR=$UINT_TEST_TOOLS_DIR/core
UNIT_TEST_TOOLS_CORE_KICKSTART_DIR=$UNIT_TEST_TOOLS_CORE_DIR/kickstart

UNIT_TEST_DIR_ALL=$UINT_TEST_SYSTEM_DIR:$UINT_TEST_LIBRARY_DIR:$UINT_TEST_LIBRARY_DIR_COMMON:$UINT_TEST_PROCESS_DIR:$UINT_TEST_MODULES_DIR:$UINT_TEST_RUNNING_DIR:$UINT_TEST_TOOLS_DIR:$UINT_TEST_TOOLS_KICKSTART_DIR:$UINT_TEST_TOOLS_KICKSTART_PARTITION_DIR:$UNIT_TEST_TOOLS_CORE_DIR:$UNIT_TEST_TOOLS_CORE_KICKSTART_DIR

#start_block

export PATH=$PATH:$SRC_DIR:$UNIT_TEST_DIR_ALL
export RUNNING_DIR=$RUNNING_DIR
export FINAL_DIR=$FINAL_DIR
#echo $PATH



source debug.sh

show_sh_begin_banner



# Replace dos2unix
#find . ! -path "*git*" -type f | sed -i 's/^M//'

sh $UNIT_TEST_DIR/unit_test.sh
if [ $? -ne 1 ];then
	print_ln LEVEL_ERROR "unit_test.sh failed"
	exit 0
fi

sh begin_clean.sh

sh insmod_exec.sh $MODULES_DIR $RUNNING_MODULES_DIR

#sh create_uefi_boot_part.sh

sh end_clean.sh



show_sh_end_banner